import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/src/app/lib/utils';
import NavBar from './components/NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={cn('relative h-full antialiased', inter.className)}>
        <NavBar />  
        <main className='relative flex flex-col min-h-screen'>
          <div className='flex-grow flex-1'>
            {children}
          </div>
        </main>
        <Analytics />
        </body>
    </html>
  )
}
